sudo: required
# dist: trusty
language: ruby
bundler_args: --without benchmarks development
# Pin Rubygems to a working version. Sometimes it breaks upstream. Update now and then.
before_install:
  - gem --version
  - gem update --system 2.6.12
  - gem update bundler
  - gem --version
  - bash .travis_setup.sh
addons:
  hosts:
    - mysql2gem.example.com
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
rvm:
  - 2.6
  - 2.5
  - 2.4
  - ruby-head
matrix:
  include:
    - rvm: 2.6
      env: DB=mysql56
      addons:
        hosts:
          - mysql2gem.example.com
    - rvm: 2.6
      env: DB=mysql57
      addons:
        hosts:
          - mysql2gem.example.com
    - rvm: 2.6
      env: DB=mysql80
      addons:
        hosts:
          - mysql2gem.example.com
    - os: osx
      rvm: system
      env: DB=mysql56
      addons:
        hosts:
          - mysql2gem.example.com
      before_install:
        # Use the system RubyGem with the system Ruby
        - gem --version
        - sudo gem install bundler
        - bash .travis_setup.sh
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - os: osx
      rvm: system
      env: DB=mysql56
    - rvm: 2.0.0
      env: DB=mysql51
      dist: precise
